[package]
authors = ["Y <j4fdot@qq.com>"]
description = "ğŸ’¹ å‘½ä»¤è¡Œ A è‚¡æ²ªæ·±åŒ—è¯è‚¡ç¥¨ä¿¡æ¯è¡Œæƒ…æ•°æ®æŸ¥è¯¢å·¥å…·"
edition = "2021"
license = "MIT"
name = "rains"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.0", features = ["derive"] }
crossterm = "0.22"
futures-util = "0.3"
http = "0.2"
once_cell = "1.9"
owo-colors = "3"
regex = "1.5"
reqwest = "0.11"
scraper = "0.12"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "*", features = ["native-tls"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
